sudo: required
services:
  - docker

before_install:
  - docker build -t hoantq3008/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run hoantq3008/react-test npm test -- --coverage

after_success:
  - docker build -t hoantq3008/multi-client ./client
  - docker build -t hoantq3008/multi-nginx ./nginx
  - docker build -t hoantq3008/multi-server ./server
  - docker build -t hoantq3008/multi-worker ./worker

  #login to docker cli
  # ( NOTE ) before using DOCKER_PASSWORD or ID, we must be add environment variable in the travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push all image build above to docker hub for elasticbeanstalk using
  - docker push hoantq3008/multi-client
  - docker push hoantq3008/multi-nginx
  - docker push hoantq3008/multi-server
  - docker push hoantq3008/multi-worker
